class DnBPrompt:
    def __init__(self):
        self.prompt= {
            "animals_scene": [
                "a cat and a dog in the library",
                "a cat and a dog in the kitchen",
                "a cat and a dog in the bedroom",
                "a cat and a dog on the bridge",
                "a cat and a dog on the street, snowy driving scene",
                "a cat and a dog on the street, rainy driving scene",
                "a cat and a dog on the street, nighttime driving scene",
                "a bird and a bear in the library",
                "a bird and a bear in the kitchen",
                "a bird and a bear in the bedroom",
                "a bird and a bear on the bridge",
                "a bird and a bear on the street, snowy driving scene",
                "a bird and a bear on the street, rainy driving scene",
                "a bird and a bear on the street, nighttime driving scene",
                "a lion and a frog in the library",
                "a lion and a frog in the kitchen",
                "a lion and a frog in the bedroom",
                "a lion and a frog on the bridge",
                "a lion and a frog on the street, snowy driving scene",
                "a lion and a frog on the street, rainy driving scene",
                "a lion and a frog on the street, nighttime driving scene",
                "a dog and a turtle in the library",
                "a dog and a turtle in the kitchen",
                "a dog and a turtle in the bedroom",
                "a dog and a turtle on the bridge",
                "a dog and a turtle on the street, snowy driving scene",
                "a dog and a turtle on the street, rainy driving scene",
                "a dog and a turtle on the street, nighttime driving scene",
                "a monkey and a rabbit in the library",
                "a monkey and a rabbit in the kitchen",
                "a monkey and a rabbit in the bedroom",
                "a monkey and a rabbit on the bridge",
                "a monkey and a rabbit on the street, snowy driving scene",
                "a monkey and a rabbit on the street, rainy driving scene",
                "a monkey and a rabbit on the street, nighttime driving scene",
                "a horse and a bird in the library",
                "a horse and a bird in the kitchen",
                "a horse and a bird in the bedroom",
                "a horse and a bird on the bridge",
                "a horse and a bird on the street, snowy driving scene",
                "a horse and a bird on the street, rainy driving scene",
                "a horse and a bird on the street, nighttime driving scene",
                "a cat and a mouse in the library",
                "a cat and a mouse in the kitchen",
                "a cat and a mouse in the bedroom",
                "a cat and a mouse on the bridge",
                "a cat and a mouse on the street, snowy driving scene",
                "a cat and a mouse on the street, rainy driving scene",
                "a cat and a mouse on the street, nighttime driving scene",
                "a dog and an elephant in the library",
                "a dog and an elephant in the kitchen",
                "a dog and an elephant in the bedroom",
                "a dog and an elephant on the bridge",
                "a dog and an elephant on the street, snowy driving scene",
                "a dog and an elephant on the street, rainy driving scene",
                "a dog and an elephant on the street, nighttime driving scene"
            ],            
            "color_objects_scene": [
                "a red cat and a blue dog in the library",
                "a red cat and a blue dog in the kitchen",
                "a red cat and a blue dog in the bedroom",
                "a red cat and a blue dog on the street, snowy driving scene",
                "a red cat and a blue dog on the street, rainy driving scene",
                "a red cat and a blue dog on the street, nighttime driving scene",
                "a purple dog and a green bench in the library",
                "a purple dog and a green bench in the kitchen",
                "a purple dog and a green bench in the bedroom",
                "a purple dog and a green bench on the street, snowy driving scene",
                "a purple dog and a green bench on the street, rainy driving scene",
                "a purple dog and a green bench on the street, nighttime driving scene",
                "a red cat and a black backpack in the library",
                "a red cat and a black backpack in the kitchen",
                "a red cat and a black backpack in the bedroom",
                "a red cat and a black backpack on the street, snowy driving scene",
                "a red cat and a black backpack on the street, rainy driving scene",
                "a red cat and a black backpack on the street, nighttime driving scene",
                "a green dog and a white clock in the library",
                "a green dog and a white clock in the kitchen",
                "a green dog and a white clock in the bedroom",
                "a green dog and a white clock on the street, snowy driving scene",
                "a green dog and a white clock on the street, rainy driving scene",
                "a green dog and a white clock on the street, nighttime driving scene",
                "a green backpack and a yellow chair in the library",
                "a green backpack and a yellow chair in the kitchen",
                "a green backpack and a yellow chair in the bedroom",
                "a green backpack and a yellow chair on the street, snowy driving scene",
                "a green backpack and a yellow chair on the street, rainy driving scene",
                "a green backpack and a yellow chair on the street, nighttime driving scene",
                "a green balloon and a pink car in the library",
                "a green balloon and a pink car in the kitchen",
                "a green balloon and a pink car in the bedroom",
                "a green balloon and a pink car on the street, snowy driving scene",
                "a green balloon and a pink car on the street, rainy driving scene",
                "a green balloon and a pink car on the street, nighttime driving scene",
                "a blue crown and a red balloon in the library",
                "a blue crown and a red balloon in the kitchen",
                "a blue crown and a red balloon in the bedroom",
                "a blue crown and a red balloon on the street, snowy driving scene",
                "a blue crown and a red balloon on the street, rainy driving scene",
                "a blue crown and a red balloon on the street, nighttime driving scene",
                "a black cat and a red suitcase in the library",
                "a black cat and a red suitcase in the kitchen",
                "a black cat and a red suitcase in the bedroom",
                "a black cat and a red suitcase on the street, snowy driving scene",
                "a black cat and a red suitcase on the street, rainy driving scene",
                "a black cat and a red suitcase on the street, nighttime driving scene",
                "a pink clock and a green apple in the library",
                "a pink clock and a green apple in the kitchen",
                "a pink clock and a green apple in the bedroom",
                "a pink clock and a green apple on the street, snowy driving scene",
                "a pink clock and a green apple on the street, rainy driving scene",
                "a pink clock and a green apple on the street, nighttime driving scene",
                "a blue bird and a brown backpack in the library",
                "a blue bird and a brown backpack in the kitchen",
                "a blue bird and a brown backpack in the bedroom",
                "a blue bird and a brown backpack on the street, snowy driving scene",
                "a blue bird and a brown backpack on the street, rainy driving scene",
                "a blue bird and a brown backpack on the street, nighttime driving scene"
            ],
                "multi_objects": [
                "one dog and two cats",
                "one dog and three cats",
                "one dog and two birds",
                "one dog and three birds",
                "one cat and two dogs",
                "one cat and three dogs",
                "one cat and two birds",
                "one cat and three birds",
                "one zebra and two birds",
                "one zebra and three birds",
                "one pineapple and two apples",
                "one pineapple and two oranges",
                "one pineapple and three apples",
                "two pineapple and two apples",
                "one banana and two apples",
                "two oranges and two apples",
                "one banana and two oranges",
                "two banana and two oranges",
                "two dogs next to a bike",
                "two cats next to a bike",
                "three zebras standing next to each other",
                "three sheep standing in the field",
                "three cows standing in the field",
                "one apple and two sandwiches",
                "one sandwich and two apples",
                "three geese floating in the middle of a river",
                "three bowls on the table",
                "one apple and two donuts",
                "one apple and three donuts",
                "two apples and two donuts"
            ]            
        }

    def __call__(self, keys):
        return self.prompt[keys]
